name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.avbharadwaj }}
          password: ${{ secrets.Bharadwaj@2026 }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.avbharadwaj }}/node-Day1-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.avbharadwaj }}/node-Day1-app:latest

